/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
  @Test public void testSomeLibraryMethod() {
    Main classUnderTest = new Main();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    //bla bla bla
    //bla bla bla 2
    
    //bla bla bla 3
    //bla bla bla 4
  }
}
