package com.github.bot.curiosone.core;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// SUPPRESS CHECKSTYLE AvoidStarImport
import static org.junit.Assert.*;

import org.junit.Test;

public class MainTest {
  @Test public void testSomeLibraryMethod() {
    Main classUnderTest = new Main();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
