/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
  public boolean someLibraryMethod() {
    return true;
  }
  public static void main(String[] args) {
    System.out.println("Hello World");
  }
}
